REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('12', 'en', 'Wrong item ordered');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('3', 'en', 'Wrong description online');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('4', 'en', 'Can\'t make it work');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('5', 'en', 'Manufacturer defect');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('6', 'en', 'Wrong item delivered');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('7', 'en', 'Out of warranty');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('8', 'en', 'Damaged during shipping');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('1', 'en', 'Replace item');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('2', 'en', 'Refund');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('13', 'en', 'Other');
REPLACE INTO ?:rma_property_descriptions (property_id, lang_code, property) VALUES ('11', 'en', 'Dead on arrival');